import type {
  BlackTonnyPageKey,
  BlackTonnyPageSpec,
  BlackTonnySummaryCardConfig,
} from '#/types/black-tonny';

export const BLACK_TONNY_SUMMARY_CARD_CONFIG: Record<
  string,
  BlackTonnySummaryCardConfig
> = {
  avg_order_value: {
    description: '销售额与订单数的配比，先判断客单是否还撑得住。',
    format: 'money',
    key: 'avg_order_value',
    label: '客单价',
    tag: '实际',
    tone: 'focus',
  },
  daily_sales_amount: {
    description: '近阶段滚动窗口内的日均销售额，用来看本周节奏。',
    format: 'money',
    key: 'daily_sales_amount',
    label: '日均销售额',
    tag: '实际',
    tone: 'neutral',
  },
  estimated_inventory_days: {
    description: '按当前销售节奏估算库存还能卖多少天。',
    format: 'quantity',
    key: 'estimated_inventory_days',
    label: '库存覆盖天数',
    tag: '估算',
    tone: 'warning',
    unit: '天',
  },
  inventory_amount: {
    description: '当前库存价值快照，先判断库存压力。',
    format: 'money',
    key: 'inventory_amount',
    label: '库存金额',
    tag: '实际',
    tone: 'critical',
  },
  inventory_kpi_current_inventory_value: {
    description: '库存价值代理口径，适合判断存货压力，不直接当成本结论。',
    format: 'money',
    key: 'inventory_kpi_current_inventory_value',
    label: '当前库存价值',
    tag: '估算',
    tone: 'critical',
  },
  inventory_kpi_days_of_cover: {
    description: '近 30 天销售承接下的可售天数。',
    format: 'quantity',
    key: 'inventory_kpi_days_of_cover',
    label: '可售天数',
    tag: '估算',
    tone: 'warning',
    unit: '天',
  },
  inventory_kpi_stock_to_sales_ratio: {
    description: '库存价值相对近 30 天销售额的压力指标。',
    format: 'quantity',
    key: 'inventory_kpi_stock_to_sales_ratio',
    label: '存销比',
    tag: '估算',
    tone: 'critical',
  },
  inventory_qty: {
    description: '当前库存件数，用来看库存体量。',
    format: 'quantity',
    key: 'inventory_qty',
    label: '库存数量',
    tag: '实际',
    tone: 'neutral',
  },
  items_per_order: {
    description: '每单带走几件，适合观察组合销售。',
    format: 'quantity',
    key: 'items_per_order',
    label: '连带件数',
    tag: '实际',
    tone: 'neutral',
  },
  member_sales_ratio: {
    description: '会员成交占比，用来看复购和会员贡献。',
    format: 'percent',
    key: 'member_sales_ratio',
    label: '会员占比',
    tag: '实际',
    tone: 'positive',
  },
  month_to_date_sales_amount: {
    description: '本月累计完成的销售额，用来看当前阶段达成。',
    format: 'money',
    key: 'month_to_date_sales_amount',
    label: '本月累计销售',
    tag: '实际',
    tone: 'focus',
  },
  negative_sku_count: {
    description: '负库存 SKU 数，优先判断库存口径是否可靠。',
    format: 'quantity',
    key: 'negative_sku_count',
    label: '负库存 SKU',
    tag: '实际',
    tone: 'critical',
  },
  sales_amount: {
    description: '当前滚动窗口的实际销售额。',
    format: 'money',
    key: 'sales_amount',
    label: '经营销售额',
    tag: '实际',
    tone: 'focus',
  },
  sales_orders: {
    description: '同口径订单量，用来看客流承接。',
    format: 'quantity',
    key: 'sales_orders',
    label: '订单数',
    tag: '实际',
    tone: 'neutral',
  },
  sales_qty: {
    description: '滚动窗口内的销售件数。',
    format: 'quantity',
    key: 'sales_qty',
    label: '销售件数',
    tag: '实际',
    tone: 'neutral',
  },
};

const tableLibrary = {
  category_risks: {
    description: '先看哪些品类库存和销售关系失衡。',
    key: 'category_risks',
    maxRows: 8,
    title: '品类风险概览',
  },
  clearance: {
    description: '今天该先停补、先前移、先去化的商品。',
    key: 'clearance',
    maxRows: 8,
    title: '去化建议',
  },
  clearance_categories: {
    description: '先按品类定去化顺序，再下钻到 SKU。',
    key: 'clearance_categories',
    maxRows: 8,
    title: '去化品类',
  },
  inventory_decisions: {
    description: '把当前 SKU 分成补货、去化、观察三类动作。',
    key: 'inventory_decisions',
    maxRows: 10,
    title: '库存决策清单',
  },
  inventory_kpi_category: {
    description: '从品类层看库存额、销售额和可售天数。',
    key: 'inventory_kpi_category',
    maxRows: 10,
    title: '品类 KPI',
  },
  inventory_kpi_sku: {
    description: '从 SKU 层看具体库存和动销表现。',
    key: 'inventory_kpi_sku',
    maxRows: 10,
    title: 'SKU KPI',
  },
  inventory_overstock_watch: {
    description: '先看哪些 SKU 已经进入积压观察。',
    key: 'inventory_overstock_watch',
    maxRows: 8,
    title: '积压观察',
  },
  inventory_restock_watch: {
    description: '先看哪些 SKU 已经逼近补货线。',
    key: 'inventory_restock_watch',
    maxRows: 8,
    title: '补货观察',
  },
  replenish: {
    description: '本阶段优先补哪些款，怎么控节奏。',
    key: 'replenish',
    maxRows: 8,
    title: '补货建议',
  },
  replenish_categories: {
    description: '先按品类结构定补货方向。',
    key: 'replenish_categories',
    maxRows: 8,
    title: '补货品类',
  },
  sales_by_category: {
    description: '看本阶段销售集中在哪些品类。',
    key: 'sales_by_category',
    maxRows: 8,
    title: '品类销售概览',
  },
} as const;

function tableSpec(key: keyof typeof tableLibrary) {
  return tableLibrary[key];
}

export const BLACK_TONNY_PAGE_SPECS: Record<
  BlackTonnyPageKey,
  BlackTonnyPageSpec
> = {
  dashboard: {
    businessGoal: '先看现状、风险和今天动作，快速确定今天优先级。',
    collapsedBlocks: ['consulting', 'relationship', 'insights'],
    expandedBlocks: [
      'todayFocus',
      'healthLights',
      'executionBoard',
      'decision',
    ],
    heroMode: 'overview',
    keyQuestions: ['今天先看什么', '今天先做什么', '经营状态是否健康'],
    pageKey: 'dashboard',
    pageSummary: '老板进入系统后的总控首页，先看经营现状、风险和动作顺序。',
    pageTitle: '经营总览',
    primaryChart: {
      chartType: 'line',
      description:
        '先判断最近销售有没有继续掉速，再决定今天是控补货还是冲营业额。',
      dimensionKey: '日期',
      rowLimit: 8,
      rowTake: 'last',
      source: {
        key: 'sales_daily',
        kind: 'table',
      },
      title: '近 8 天销售走势',
      valueKeys: ['销售额', '订单数'],
    },
    shellKind: 'dashboard',
    summaryPriority: [
      'sales_amount',
      'month_to_date_sales_amount',
      'inventory_amount',
      'estimated_inventory_days',
      'member_sales_ratio',
      'avg_order_value',
      'sales_orders',
      'negative_sku_count',
    ],
    tableOrder: [
      tableSpec('inventory_decisions'),
      tableSpec('replenish'),
      tableSpec('clearance'),
    ],
  },
  details: {
    businessGoal: '把问题定位到品类、SKU 和库存结构，知道先查哪里。',
    collapsedBlocks: ['healthLights', 'relationship', 'insights'],
    expandedBlocks: ['todayFocus', 'decision', 'consulting'],
    heroMode: 'analysis',
    keyQuestions: ['问题出在哪个品类', '问题出在哪个 SKU', '库存结构哪里失衡'],
    pageKey: 'details',
    pageSummary: '经营问题的明细核查页，重点看品类 KPI、SKU 表现和库存决策。',
    pageTitle: '经营明细',
    primaryChart: {
      chartType: 'bar',
      description: '先看哪几个中类库存额高、但近 30 天销售额承接偏弱。',
      dimensionKey: '中类',
      rowLimit: 8,
      rowTake: 'first',
      source: {
        key: 'inventory_kpi_category',
        kind: 'table',
      },
      title: '品类库存额与近 30 天销售额',
      valueKeys: ['库存额', '近30天销售额'],
    },
    shellKind: 'standard',
    summaryPriority: [
      'inventory_amount',
      'inventory_qty',
      'negative_sku_count',
      'inventory_kpi_days_of_cover',
      'daily_sales_amount',
      'sales_qty',
      'avg_order_value',
      'member_sales_ratio',
    ],
    tableOrder: [
      tableSpec('inventory_kpi_category'),
      tableSpec('inventory_kpi_sku'),
      tableSpec('inventory_decisions'),
    ],
  },
  monthly: {
    businessGoal:
      '围绕本月节奏安排动作，知道这 30 天该补什么、清什么、盯什么。',
    collapsedBlocks: ['healthLights', 'consulting', 'insights'],
    expandedBlocks: ['todayFocus', 'executionBoard', 'decision'],
    heroMode: 'execution',
    keyQuestions: [
      '本月节奏正常吗',
      '本月先推进什么动作',
      '本月补货和去化谁更优先',
    ],
    pageKey: 'monthly',
    pageSummary: '近 30 天执行页，重点看月度节奏、补货建议和去化动作。',
    pageTitle: '月度执行',
    primaryChart: {
      chartType: 'line',
      description:
        '看月内销售节奏是否稳定，判断当前执行动作该偏冲量还是控折扣。',
      dimensionKey: 'label',
      rowLimit: 6,
      rowTake: 'last',
      source: {
        kind: 'path',
        path: [
          'summary_cards',
          'yeusoft_highlights',
          'sales_overview',
          'monthly_rows',
        ],
      },
      title: '月度销售节奏',
      valueKeys: ['sales_amount', 'order_count'],
    },
    shellKind: 'standard',
    summaryPriority: [
      'month_to_date_sales_amount',
      'daily_sales_amount',
      'sales_orders',
      'avg_order_value',
      'member_sales_ratio',
      'estimated_inventory_days',
      'inventory_amount',
      'negative_sku_count',
    ],
    tableOrder: [
      tableSpec('replenish'),
      tableSpec('clearance'),
      tableSpec('sales_by_category'),
    ],
  },
  quarterly: {
    businessGoal: '从阶段视角看结构和动作，知道下阶段该调哪里。',
    collapsedBlocks: ['todayFocus', 'executionBoard', 'insights'],
    expandedBlocks: ['decision', 'relationship', 'consulting'],
    heroMode: 'strategy',
    keyQuestions: [
      '当前阶段结构是否健康',
      '下阶段重点该放哪',
      '哪些品类需要先调',
    ],
    pageKey: 'quarterly',
    pageSummary: '季度复盘与阶段策略页，重点看结构、阶段结论和下阶段动作。',
    pageTitle: '季度复盘',
    primaryChart: {
      chartType: 'bar',
      description:
        '站在阶段视角看季度销售额和订单量，判断下阶段策略是否需要调整。',
      dimensionKey: 'label',
      rowLimit: 6,
      rowTake: 'last',
      source: {
        kind: 'path',
        path: [
          'summary_cards',
          'yeusoft_highlights',
          'sales_overview',
          'quarterly_rows',
        ],
      },
      title: '季度销售观察窗口',
      valueKeys: ['sales_amount', 'order_count'],
    },
    shellKind: 'standard',
    summaryPriority: [
      'month_to_date_sales_amount',
      'inventory_amount',
      'estimated_inventory_days',
      'member_sales_ratio',
      'avg_order_value',
      'items_per_order',
      'sales_orders',
      'negative_sku_count',
    ],
    tableOrder: [
      tableSpec('inventory_kpi_category'),
      tableSpec('replenish_categories'),
      tableSpec('clearance_categories'),
    ],
  },
  relationship: {
    businessGoal:
      '先判断哪些品类积压、哪些该补、哪些结构失衡，再决定动作顺序。',
    collapsedBlocks: ['todayFocus', 'consulting', 'insights'],
    expandedBlocks: ['healthLights', 'executionBoard', 'relationship'],
    heroMode: 'relationship',
    keyQuestions: ['哪些品类积压', '哪些品类该补', '哪些结构已经失衡'],
    pageKey: 'relationship',
    pageSummary: '库销关系决策页，聚焦补货、去化和结构失衡。',
    pageTitle: '库销关系',
    primaryChart: {
      chartType: 'bar',
      description: '先看哪个大类库存额高、但零售额承接不足。',
      dimensionKey: '大类',
      rowLimit: 8,
      rowTake: 'first',
      source: {
        key: 'category_risks',
        kind: 'table',
      },
      title: '库销关系矩阵',
      valueKeys: ['库存额', '零售额'],
    },
    shellKind: 'standard',
    summaryPriority: [
      'inventory_kpi_current_inventory_value',
      'inventory_kpi_days_of_cover',
      'inventory_kpi_stock_to_sales_ratio',
      'negative_sku_count',
      'inventory_amount',
      'inventory_qty',
      'member_sales_ratio',
      'month_to_date_sales_amount',
    ],
    tableOrder: [
      tableSpec('category_risks'),
      tableSpec('inventory_restock_watch'),
      tableSpec('inventory_overstock_watch'),
    ],
  },
};
